# Netlify Build Configuration
[build]
  # Build command - runs when deploying
  command = "npm run build"
  
  # Publish directory - where the built files are located
  publish = "dist"
  
  # Node.js version to use during build
  [build.environment]
    NODE_VERSION = "20"
    NPM_VERSION = "10"

# Redirect all routes to index.html for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Development context (for branch previews)
[context.development]
  command = "npm run build"
  
# Production context
[context.production]
  command = "npm run build"

# Deploy previews context
[context.deploy-preview]
  command = "npm run build"